import {Platform} from 'react-native';
import {scale} from 'react-native-size-matters';
import styleFrom from '../../assets/styles/styles';
const styles = {
  safeView: {
    flex: 1,
    backgroundColor: '#f9f9f9',
  },
  headerBar: {
    height: 60,
    width: '100%',
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
  },
  menuView: {
    width: '20%',
    height: 33,
    borderRadius: 12,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  greetingText: {
    color: styleFrom.SecondaryGrey,
    fontSize: 14,
    textTransform: 'uppercase',
    fontWeight:"600"
  },
  greetingTitle: {
    color: styleFrom.navyBlue,
    fontSize: 32,
    fontWeight: 'bold',
  },
  greetingSearch: {
    width: '92%',
    borderWidth: 0.5,
    borderColor: '#F2F2F2',
    borderRadius: 10,
    flexDirection: 'row',
    backgroundColor: '#fbfbfb',
    marginLeft: 15,
    marginRight: 15,
    marginBottom: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchBtn: {
    backgroundColor: '#000',
    borderRadius: 8,
    flex: 0.08,
    marginRight: 8,
  },
  searchIcon: {
    height: 15,
    width: 15,
    margin: 5,
  },
  categoryView: {
    backgroundColor:'#fff',
    borderRadius: 8,
    flex: 0.1,
    //flexDirection: 'Column',
    marginLeft: 15,
    marginRight: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  subCategoryView: {
    flex: 0.6,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
    
  },
  categoryBtn: {
    borderRadius: 30,
    height: 58,
    width: 58,
    justifyContent: 'center',
    alignItems: 'center',
  },
  seeallBtn: {
    flex: 0.25,
    height: 30,
    width: 70,
    backgroundColor: styleFrom.white,
    borderWidth: 2,
    borderColor: styleFrom.mediumGrey,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  seeallTextView: {
    justifycontent: 'center',
    alignItems: 'center',
  },
  seeallText: {
    fontSize: 12,
    width: '100%',
    marginLeft: 5,
    fontWeight: '600',
    color: '#6F767E',
  },
  greetingView: {
    backgroundColor: '#fff',
    flex: 0.2,
    margin: 15,
    borderRadius: 10,
  },
  currentLocationText: {
    fontSize: 10,
    color: '#636A75',
  },
  locationText: {
    fontSize: 14,
    color: styleFrom.navyBlue,
  },
  arrowText: {
    left: 5,
    marginTop: 2,
  },
  flatlistView: {
    margin: 10,
    alignItems: 'center',
  },
  flatlistImage: {
    width: 170,
    height: 170,
    borderRadius: 15,
  },
  flatlistText: {
    fontWeight: '600',
    fontSize: 14,
    marginTop:10,
    color: styleFrom.subTitleblue,
  },
  flatlistView1: {
    margin: 10,
    alignItems: 'center',
  },
  flatlistImage1: {
    width: 200,
    height: 170,
    borderRadius: 15,
  },
  trendingText: {
    color: styleFrom.Indigo,
    fontWeight: '700',
    marginBottom:7,
    marginLeft:10,
    fontSize: 20,
  },
  modal_container: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.8)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modal_View: {
    flex: 0.55,
    width: '90%',
    borderRadius: 20,
    backgroundColor: styleFrom.white,
    alignItems: 'center',
  },
  subCategoryText: {
    fontSize: 13,
    color: styleFrom.blueText,
    marginTop:5
  },
  subCategoryStyle: {
    height: 30,
    width: 30,
  },
  trendingServiceView: {
    marginLeft: 15,
    marginRight: 15,

  },
  CleaningView: {
    flexDirection: 'row',
    margin: 10,
    alignItems: 'center',
  },
  CleaningView1: {
    //flexDirection: 'row',
    //margin: 10,
   // alignItems: 'center',
  },
  cleaningbgView: {
    flex: 0.5,
    backgroundColor: '#fff',
    marginTop: 15,
    marginLeft: 15,
    marginRight: 15,
    borderRadius: 8,
  },
  cleaningServiceText: {
    color: styleFrom.titleBlue,
    fontSize: 18,
    marginLeft: 10,
    flex: 0.85,
    fontWeight: '600',
  },
  cleaningImgStyle: {
    height: 20,
    width: 4,
  },
  arrowStyle: {
    height: 20,
    width: 25,
  },
  modalClose: {
    borderRadius: 20,
    backgroundColor: '#EBEBEB',
    height: 30,
    width: 30,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 10,
  },
  button: {
    height: '12%',
    width: '80%',
    marginTop: 20,
    backgroundColor: styleFrom.black,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  flatlistTextStyle: {
    fontWeight: '700',
    fontSize: 14,
    color: '#fff',
    position: 'absolute',
    bottom: 10,
  },
  selectLocationText: {
    fontWeight: '600',
    fontSize: 18,
    color: styleFrom.Indigo,
  },
  searchView: {
    height: '20%',
    width: '100%',
    marginTop: Platform.OS === 'android' ? 10 : 15,
    marginBottom: 10,
    flexDirection: 'row',
    borderColor: styleFrom.borderColor,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addressView: {
    flexDirection: 'row',
    borderBottomColor: '#EBEBEB',
    borderBottomWidth: 0.8,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  locationView: {
    height: '25%',
    width: '65%',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  modalImageView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  locationImage: {
    height: 20,
    width: 20,
    marginBottom: 32,
    flex: 0.05,
  },
  modalImageStyle: {
    width: 100,
    height: 110,
    left: 20,
  },
  modalbgView: {
    flex: 0.8,
    flexDirection: 'row',
  },
  textView: {
    flexDirection: 'column',
    flex: 0.9,
    marginBottom: 20,
    marginLeft: 10,
  },
  currentAddress: {fontWeight: '500', fontSize: 16, color: '#000'},
  detailedAddress: {
    fontWeight: '400',
    fontSize: 14,
    color: styleFrom.iconColor,
    width: '65%',
    marginTop: Platform.OS === 'android' ? 0 : 8,
  },
  buttonStyle: {
    height: '12%',
    width: '80%',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  buttonLabelStyle: {
    fontWeight: '700',
    fontSize: 16,
  },
  buttonTextStyle: {
    fontSize: 14,
    fontWeight: '500',
  },
  locationModalText: {
    fontWeight: '500',
    fontSize: 15,
    color: styleFrom.Indigo,
  },
  allowLocation: {
    fontWeight: '700',
    fontSize: 16,
    color: styleFrom.Indigo,
  },
  bottomview: {
    flex: 0.5,
    width: '100%',
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    backgroundColor: styleFrom.white,
  },
  mapview: {
    flex: 0.45,
    width: '100%',
    bottom: -35,
    borderRadius:10,
    backgroundColor: styleFrom.white,
  },
  mapmodel_container: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'flex-end',
    borderRadius:10
  },
};
export default styles;
