const images = {
    remove: require('../../../assets/image/remove.png'),
    backarrow: require('../../../assets/image/backarrow.png'),
    creditcard: require('../../../assets/image/credit-card.png'),
    debitcard: require('../../../assets/image/debit-card.png'),
    money: require('../../../assets/image/money.png'),
    eyeclose: require("../../../assets/image/eyeclose.png"),
    eyeon: require("../../../assets/image/eyeon.png"),
    splashbg: require("../../../assets/image/splashbg.png"),
    splashBgTheme: require('../../../assets/image/splashBgTheme.png'),
    horfayLogo: require('../../../assets/image/horfayLogo.png'),
    HaLogo: require('../../../assets/image/HaLogo.png'),
    imageborder: require("../../../assets/image/refundimage_border.png"),
    seleced_service: require("../../../assets/image/selected_services.png"),
    facial: require("../../../assets/image/goldFacial.png"),
    map_marker: require('../../../assets/image/MapMarker.png'),
    thumbsup: require("../../../assets/image/Thumbsup.png"),
    dotimg: require("../../../assets/image/dotimg.png"),
    round: require("../../../assets/image/round.png"),
    kyc_image: require('../../../assets/image/kyc_Image.png'),
    frontcard: require("../../../assets/image/frontcard.png"),
    backcard: require("../../../assets/image/cardback.png"),
    gps: require("../../../assets/image/gbs.png"),
    clock:  require("../../../assets/image/clock.png"),
}
export default images;
